apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-load-balancer-controller
  namespace: kube-system
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::399817749711:role/eksctl-hackathon-eks-dev-addon-iamserviceaccount-kube-system-aws-load-balancer-controller
